// <auto-generated />
using System;
using HomeFinder.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeFinder.Migrations
{
    [DbContext(typeof(DbContextClass))]
    [Migration("20241007173046_AddHouseTable")]
    partial class AddHouseTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeFinder.Domain.Models.House", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("integer");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("integer");

                    b.Property<int>("ConstructionYear")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsFavorited")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("PricePerSqr")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Houses");
                });

            modelBuilder.Entity("HomeFinder.Domain.Models.QueryField", b =>
                {
                    b.Property<int>("QueryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QueryId"));

                    b.Property<string[]>("Availability")
                        .HasColumnType("text[]");

                    b.Property<string>("Geo_lat_from")
                        .HasColumnType("text");

                    b.Property<string>("Geo_lat_to")
                        .HasColumnType("text");

                    b.Property<string>("Geo_lng_from")
                        .HasColumnType("text");

                    b.Property<string>("Geo_lng_to")
                        .HasColumnType("text");

                    b.Property<int?>("MaxBathrooms")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxBedrooms")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxConstruction_year")
                        .HasColumnType("integer");

                    b.Property<string>("MaxEnergyClass")
                        .HasColumnType("text");

                    b.Property<int?>("MaxLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxPrice")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxPricePerUnitArea")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxSize")
                        .HasColumnType("integer");

                    b.Property<int?>("MinBathrooms")
                        .HasColumnType("integer");

                    b.Property<int?>("MinBedrooms")
                        .HasColumnType("integer");

                    b.Property<int?>("MinConstruction_year")
                        .HasColumnType("integer");

                    b.Property<string>("MinEnergyClass")
                        .HasColumnType("text");

                    b.Property<int?>("MinLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("MinPrice")
                        .HasColumnType("integer");

                    b.Property<int?>("MinPricePerUnitArea")
                        .HasColumnType("integer");

                    b.Property<int?>("MinSize")
                        .HasColumnType("integer");

                    b.HasKey("QueryId");

                    b.ToTable("QueryFields");
                });
#pragma warning restore 612, 618
        }
    }
}
